### PR TITLE
add arw_compressor

### PR DESCRIPTION
**Pull request by goblin**
Adding my set of tools to compress/decompress Sony ARW files with the help of FLIF. As suggested in https://github.com/goblin/arw_compressor/issues/1 :-)

Happy to fix things around if you want more docs or cleaner code -- just let me know.

Thanks!

### CODE REVIEW

**Comment by jonsneyers** [comment]
Thanks! Looks like a great tool for Sony ARW archiving!

**Comment by StephanBusch** [comment]
Thank you very much Goblin :)
I was looking forward to this since I bought a Sony a55.
How can I run this on Windows? Does a compiled binary exist?

**Comment by goblin** [comment]
@StephanBusch no, unfortunately there aren't :-( I'm more of a linux guy.

Few years back I saw Windows has Cygwin, which is a shell that made me feel kinda like on Linux. If you're comfortable with the command line, I think it should be possible to compile these two things and use them. You'd have to install all the needed tools (tar, xz, sha256sum, and of course flif), but I don't see a reason why it shouldn't work (it's pretty much standard C, doesn't have any dependencies, etc).

An alternative is to use mingw, which I'm not very knowledgeable about.

**Comment by StephanBusch** [comment]
thanks for the info, Goblin.
would you please tell me how well this file would be compressed?
https://drive.google.com/file/d/0ByLIAFlgldSoYVJPVmZ6cXNtSEE/view?usp=sharing

**Comment by StephanBusch** [comment]
ARW compresses better with LZMA and lc=8 lp=4 pb=4 than they do with standard switches.
This indicates it has groups aligned for x16 bytes and it is a hint to the delta curve Sony uses here.
I discovered that the same switches compress Panasonic .RW2 raw files significantly better.
Is the same delta curve applied on .RW2 images?

**Comment by goblin** [comment]
@StephanBusch your file compressed down to 13 854 720 bytes with my method (81.3% of original).

There is one caveat, ARW has some padding at the end, both Sony A37 and A77 tend to add a bunch of zeroes there, whereas your camera adds 0xFF instead. Therefore my tool will break saying it found a data mismatch. It's the same number of bytes, just different values. I can add functionality that detects and stores that if you want.

I confirm 16-byte alignment makes sense for ARW files.

The LZMA options you specified don't seem to work for me, maybe I'm doing something wrong:

```
$ xz --format=raw --lzma2=preset=9,lc=8,lp=4,pb=4 --suffix=.lzma9 sony.arw 
xz: Value of the option `lc' must be in the range [0, 4]
$ xz --format=raw --lzma2=preset=9,lc=4,lp=4,pb=4 --suffix=.lzma9 sony.arw 
xz: The sum of lc and lp must not exceed 4
```

Compressing with `xz --format=raw --lzma2=preset=9 --suffix=.lzma9 sony.arw` resulted in a file that's 16 130 946 bytes long (94.7% of original).

**Comment by StephanBusch** [comment]
Thank you for the info.
Please add that functionality that detects and stores that padding.
lc=8 lp=4 pb=4 can only be used with LZMA (LZMA SDK or 7-Zip);
XZ uses LZMA2 which does not allow lc=8.

**Comment by goblin** [comment]
Hm, I thought they're using the same algorithm, only different storage formats. I have 7-zip, but can't seem to find switches that would allow passing of these arguments, what command-line are you using with `7za`?

**Comment by StephanBusch** [comment]
7za a -m0=LZMA:lc8:lp4:pb4 archive.7z a55.arw

**Comment by goblin** [comment]
Thanks @StephanBusch indeed this method works, and produces an archive of 14 590 146 bytes, which is 85.6% of original. Much better than the default xz I tried indeed, but not quite as good as FLIF.

Meanwhile I've added support for 0xFF padding so your file now compresses without issues. See https://github.com/FLIF-hub/FLIF/pull/251 or https://github.com/goblin/arw_compressor/commit/c61f029f4cf637fd69733a4fb0bc40d287bb39f8 .

**Comment by goblin** [comment]
@StephanBusch very interesting find about this 7-zip stuff... I somehow believed LZMA2 was meant to be superior in all the ways from LZMA1, and that xz actually supported LZMA1 too. Clearly wrong on both counts :-)

Best I could do with `xz` was `--lzma2=preset=9,lc=0,lp=4,pb=4`, which resulted in a file 15 351 952 bytes long (90.1%). Maybe some smart filter could help, but I'm not sure about it as ARW already seems to be using a delta-like encoding.

**Comment by StephanBusch** [comment]
Thanks @goblin 

Could you please investigate if your ARW recompressor would also work on RW2 images
or at least decoding would be possible?

**Comment by goblin** [comment]
I might have a look at this in the future, but I'm not currently planning to do it. Would be nice to have compressors for all formats, but I'm not in the position to develop them all.

**Comment by StephanBusch** [comment]
I see..

**Comment by StephanBusch** [comment]
@goblin 
Schnaader would want to add your arw recompressor to this GitHub project Precomp.
https://github.com/schnaader/precomp-cpp/issues/32
Would you allow him to use it?

**Comment by goblin** [comment]
@StephanBusch yeah done :-)

**Comment by StephanBusch** [comment]
If you would enable use of raw2rggb in that tool chain, it might improve compression noticeably.
https://github.com/FLIF-hub/FLIF/tree/master/raw-tools
Could you please give it a try?

**Comment by goblin** [comment]
@StephanBusch I'm not quite sure what raw2rggb accomplishes for the ARW toolchain, it seems to be a shell script that invokes dcraw... my toolchain uses a modified dcraw to allow to recreate the original ARW.

Does FLIF compress RGGB better than an identical RGBA (where the second green is stored in the alpha channel)?

If so I guess I could rearrange the bytes and try to tell FLIF that it's RGGB, but that sounds a little weird (if RGGB compresses better than RGBA shouldn't FLIF detect that and use whatever's smallest?)

I don't see what I could use the raw2rggb script for, I know the color arrangement pattern for ARWs (I hope it's the same everywhere), and that seems to be the main thing it tries to do.

**Comment by jonsneyers** [comment]
There is no real difference between RGGB and RGBA with `--keep-invisible-rgb`, but the order of the channels does make a (minor) difference on compression and the raw2rggb script tries to make sure that a good order gets used.

Storing the second Green in Alpha is probably not the optimal thing to do; you may want to try all permutations on some test set of ARW files in order to figure out which ordering works best.

We are currently reordering RGGB to GBGR since that seemed to work best at the time:
https://github.com/FLIF-hub/FLIF/blob/master/src/image/image-rggb.cpp#L205

Ideally, the encoder would somehow figure out the best channel permutation and use that, but that's not implemented yet (and it would have a potentially bad impact on progressive previews).
The format itself does (since recently) have a PlanePermute transform (currently not really used by the encoder), so it is something that can be done later without breaking the bitstream.
There's also PlanePermuteSubtract (which subtracts plane 0 from the other planes), which is used by default now if you disable YCoCg with `-Y`: it then permutes RGB to GRB and with the subtraction it effectively stores G (R-G) (B-G).

So for RGGB data  (ARW or otherwise), we might want to try that, e.g. store it as G1G2BR, then use the `-Y` option to permute it to G2 (G1-G2) (B-G2) R.

**Comment by StephanBusch** [comment]
Would it be possible and would you be interested to add support for further formats such as Nikon .NEF and Canon .Cr2?
I am so curious..

**Comment by bumblebritches57** [comment]
Franly, he shouldn't add support for formats like this at all.

LibRAW exists, use it.

**Comment by StephanBusch** [comment]
LibRAW is not lossless - it cannot restore raw that have been processed with it,
but this tool can and there is nothing like that

**Comment by bumblebritches57** [comment]
What exactly do you mean by that? Are you saying that the two green channels are combined, or is there something fundamentally wrong with it?

Also, why the hell not just fix the issue with libRAW instead of writing brand new programs from scratch?

**Comment by goblin** [comment]
@StephanBusch I've not looked into .NEF or .CR2 yet. While I would like to be able to compress them in a similar manner as .ARW, I don't own neither a Nikon nor a Canon camera so it's not a priority for me :-) But I might have a look in the future (no promises though).

@bumblebritches57 after a brief look, it looks like libRAW doesn't support writing of RAW files, please correct me if I'm wrong. To answer the second question, firstly: I wasn't aware of  libRAW's existence when I wrote it; secondly, it's sometimes easier and faster to hack up something small and maintainable than to learn an existing large library and try to modify it drastically (I mean adding support for writing RAWs). Having said that, such functionality would be nice to have in a library and I would be happy to try to add it in the future if libRAW's maintainers think so too and would be willing to help.

**Comment by bumblebritches57** [comment]
I know how to program, and therefore how hard it is to using a third party library. I just think for such a big project learning to use the library would have much better bang for the buck than trying to do it on your own.

To be fair I only have a passing familiarity of LibRAW, I haven't personally used it in any of my projects, but I have used it to decode a few RAW files.

**Comment by StephanBusch** [comment]
@goblin

World you please post the archive that your arw compressor creates from this File? 
https://drive.google.com/file/d/0ByLIAFlgldSoYVJPVmZ6cXNtSEE/view?usp=sharing

I would like to do some tests to see which general purpose algorithm would do better than xz

**Comment by StephanBusch** [comment]
@goblin 
please add support for those Sony a55 arw - some cause a file mismatch:
https://drive.google.com/file/d/0ByLIAFlgldSoZGtoSlBZaTM3QUE/view?usp=sharing

**Pull request merged**
