### PR TITLE
Fixed extension for OS X

### PR DESCRIPTION
**Pull request by bumblebritches57**
I put the version number before the extension, because the other way is
just dumb.

I've been sitting on this patch for a long ass time and it's just time I push it upstream.

### CODE REVIEW

**Comment by sipa** [comment]
At least on Linux, the version number goes after the extension. From my `/usr/lib`:
```
...
-rw-r--r--   1 root root  146360 Jan 31  2016 libnetpbm.so.10.0
-rw-r--r--   1 root root 4119660 Oct 26  2014 libntl.a
lrwxrwxrwx   1 root root      15 Oct 26  2014 libntl.so -> libntl.so.5.0.0
lrwxrwxrwx   1 root root      15 Oct 26  2014 libntl.so.5 -> libntl.so.5.0.0
-rw-r--r--   1 root root 1891264 Oct 26  2014 libntl.so.5.0.0
...
```

I think the right solution is using a build system that supports more systems instead of a Makefile that hardcodes everything one way or another.

**Comment by bumblebritches57** [comment]
KK. I'll go ahead and add an OS detection function, and a variable for the Version+Extension.

**Comment by jonsneyers** [comment]
Now you're hardcoding the .VERSION.EXTENSION convention though, while on Linux the convention is .EXTENSION.VERSION.

There already is OS detection in the Makefile to set the extension to .dylib instead of .so on Darwin. I'll do the changes you want by adding another variable.

**Comment by bumblebritches57** [comment]
Your change is basically the same one I made, I'll push it to my repo now.

**Comment by bumblebritches57** [comment]
Apparently I got sidetracked with my own project and forgot to push it after testing.

**Pull request closed without merging**
