### PR TITLE
faster preview stages: cloning and interpolation

### PR DESCRIPTION
**Pull request by hrj**
Two ideas to make previews faster:
* Copy only the decoded pixels into the preview image.
* Rearrangement and refactor of inner loops during interpolation

~Together, these give about 64% to 84% reduction in preview times.~
With these changes, the preview time is about 64% - 84% of earlier preview time.

For #333

### CODE REVIEW

**Comment by hrj** [comment]
Benchmark results using PolyFLIF (refer #333):

lenna
street
2k-2k

**Comment by SaschaNaz** [comment]
I think you meant (100-84)% to (100-64)% reduction, based on your [last benchmark](https://github.com/FLIF-hub/FLIF/issues/333#issuecomment-293881268)? Still impressive result :D

**Comment by hrj** [comment]
@SaschaNaz Yeah, my own wording confuses me a bit :smile:  I meant to say, the time spent in preview is now 64% to 84% of the time spent previously.

**Comment by jonsneyers** [comment]
Very nice!

**Pull request merged**
