### PR TITLE
[RAW]CFA Pattern detection in FLIF for image-rggb.cpp

### PR DESCRIPTION
**Pull request by psykauze**
Also, handle PNM comments.

### CODE REVIEW

**Comment by jonsneyers** [comment]
Nice!

**Comment by psykauze** [comment]
I know. image-rggb.cpp is a crappy sandbox now :D I think it should be better to make the magic number detection an image.cpp function and make flif use it instead of extension detection.

**Comment by jonsneyers** [comment]
Yes, ignoring extensions and using magic would be better.

It's nice that different CFA patterns can be read now, without needing rotation/flipping...

**Comment by psykauze** [comment]
Thank's but it still need a script for detecting the pattern and put it as a comment in the pgm file. Also, convert it back to RGGB will change the CFA pattern so it is lossy. The only things better it's 1) no rotation and 2) Same plane order when converted as pam or PNG.

**Pull request merged**
