### PR TITLE
Issue decode_over=true when quality is 10000

### LINKED ISSUE #411: Setting first callback quality as 10000 does not give decode_over=true
It seems high value for first callback quality causes decode_over value never be true.

### PR DESCRIPTION
**Pull request by SaschaNaz**
Fixes #411.

### CODE REVIEW

**Comment by hrj** [comment]
If `decode_over = qual==10000`, then the need for a separate `decode_over` parameter goes off, because callback can easily do the computation itself.

The `decode_over` parameter needs to convey more information than the `qual` parameter.

Currently, `decode_over` is true when then decoding is completed but qual is *not* 10000. This can be used by the client to decide whether the decoded image should be rendered or not. If decoding is over there is no point in waiting for the next callback. If decoding is not over, it may decide to pospone the rendering until next callback.

**Comment by SaschaNaz** [comment]
>Currently, decode_over is true when decoding is completed but qual is not 10000

I think it will still be true, in my test decoding a broken file always hits [line 1406 with decode_over=true](https://github.com/SaschaNaz/FLIF/blob/f89b9145b74847e3ebc8d2256ef8f36df85cca57/src/flif-dec.cpp#L1406). Is there some situation that this line will be skipped?

**Comment by hrj** [comment]
> Is there some situation that this line will be skipped?

Yes, if the file is truncated in such a way that the callback is issued from inner loop, but does not make any further progress in quality. Then no other callbacks would be issued. But that is a separate issue which needs to be addressed.

As for this PR, I agree it makes things more consistent, but it is not necessary. Client can infer the same by looking at `qual` parameter. If the PR is merged, it changes the API slightly, so I suggest a bump of version number, atleast a bump of minor version number.

**Comment by SaschaNaz** [comment]
>Yes, if the file is truncated in such a way that the callback is issued from inner loop, but does not make any further progress in quality.

I think that was my previous concern. In reality it seems it issues double callbacks where both have the same quality value.

**Comment by SaschaNaz** [comment]
>If the PR is merged, it changes the API slightly, so I suggest a bump of version number, atleast a bump of minor version number.

Should I do bump it on this PR or you will do it later?

**Comment by hrj** [comment]
> I think that was my previous concern. In reality it seems it issues double callbacks where both have the same quality value.

Oh! Would be nice to have a reproducible test case, using something like `dumpflif`.

> Should I do bump it on this PR or you will do it later?

I am not sure if @jonsneyers would like a version bump. It was just a suggestion from my end.

**Comment by SaschaNaz** [comment]
>Oh! Would be nice to have a reproducible test case, using something like dumpflif.

#433

**Comment by hrj** [comment]
@jonsneyers I guess it is okay to merge. The callback logic needs to be further fixed anyway (#433), so the version bump can happen later.

**Pull request merged**
